# ===============================
# CONFIGURACAO DO BANCO (PostgreSQL)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/subfy
spring.datasource.username=postgres
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# SERVER
# ===============================
server.port=8080

# ===============================
# JWT
# ===============================
jwt.secret=subfySecretKey123456789
jwt.expiration=86400000

# ===============================
# EMAIL SMTP (Gmail)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=matteoscaetano@gmail.com
spring.mail.password=ndzrpcbchoqubyb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true